import Data from "../types";
import UpdateStateData, { Game, Player, Team } from "../types/updateState";
import TestPlayer from "./Player";

export const PLAYER_NAMES = [
  "Armstrong",
  "Bandit",
  "Beast",
  "Boomer",
  "Buzz",
  "C-Block",
  "Casper",
  "Caveman",
  "Centice",
  "Chipper",
  "Cougar",
  "Dude",
  "Foamer",
  "Fury",
  "Gerwin",
  "Goose",
  "Heater",
  "Hollywood",
  "Hound",
  "Iceman",
  "Imp",
  "Jester",
  "Junker",
  "Khan",
  "Marley",
  "Maverick",
  "Merlin",
  "Middy",
  "Mountain",
  "Myrtle",
  "Outlaw",
  "Poncho",
  "Rainmaker",
  "Raja",
  "Rex",
  "Roundhouse",
  "Sabretooth",
  "Saltie",
  "Samara",
  "Scout",
  "Shepard",
  "Slider",
  "Squall",
  "Sticks",
  "Stinger",
  "Storm",
  "Sultan",
  "Sundow",
  "Swabbie",
  "Hog Tex",
  "Tusk",
  "Viper",
  "Wolfman",
  "Yuri",
];

export const TEAM_NAMES = [
  "Calm Pigs",
  "Angry Dogs",
  "Wild Mambas",
  "Powerful Deer",
  "Fast Sparrows",
  "Quick Dodgers",
  "Deadly Riddles",
  "True",
  "Rough Gnomes",
  "Infamous Swallows",
  "Crows",
  "Clever Leopards",
  "Robins",
  "Quiet Kings",
  "Fabulous Vultures",
  "Pure Bears",
  "Big Comets",
  "Clever Doves",
  "Brave Serpents",
  "Stark Chimpanzees",
  "Grand Raccoons",
  "Bitter Pandas",
  "Brave Dinos",
  "Iron Pythons",
  "Crusaders",
  "Major Lobsters",
  "Big Bad Camels",
  "Dapper Birds",
  "Extraordinary Enigmas",
  "Stark Prowlers",
  "Monstrous Boomers",
  "Crunchers",
  "Black Pelicans",
  "Cats",
  "Majestic Chimpanzees",
  "Seals",
  "Storm Wolves",
  "Careless Crusaders",
  "Infamous Mammoths",
  "Creative Camels",
];
